<?php

$nilai = 90;
$absen = 90;

if ($nilai >= 80 && $absen >= 80) {
    echo "Selamat Anda Lulus Dengan Nilai A" . PHP_EOL;
} else if ($nilai >= 70 && $absen >= 70) {
    echo "Selamat Anda Lulus Dengan Nilai B" . PHP_EOL;
} else if ($nilai >= 60 && $absen >= 60) {
    echo "Selamat Ada Lulus Dengan Nilai C" . PHP_EOL;
} else if ($nilai >= 50 && $absen >= 50) {
    echo "Selamat Anda Lulus Dengan Nilai D" . PHP_EOL;
} else {
    echo "Mohon Maaf Anda Harus Mengulang Karena Nilai Anda E" . PHP_EOL;
}

